# Generated by Django 3.0.6 on 2020-07-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('codigo_boleta', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_emision', models.DateField()),
                ('nombre_producto', models.CharField(max_length=30)),
                ('cant_producto', models.IntegerField(default=0)),
                ('monto_unitario', models.IntegerField(default=0)),
                ('monto_total', models.IntegerField(default=0)),
                ('forma_pago', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Moroso',
            fields=[
                ('rut_cliente_moroso', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30, null=True)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('autorizacion_fiado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_Cliente_Moroso',
            fields=[
                ('numero_ficha', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30, null=True)),
                ('moras_atraso', models.IntegerField()),
                ('cantidad_pedidos_fiados', models.IntegerField()),
                ('fecha_integracion_cliente', models.DateField()),
                ('rut_cliente_moroso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyos.Cliente_Moroso')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_producto', models.CharField(max_length=90)),
                ('fecha_vencimiento', models.DateField()),
                ('tipo_producto', models.CharField(max_length=50)),
                ('precio_unitario', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('razon_social', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_prov', models.CharField(max_length=50)),
                ('Nombre_Representante', models.CharField(max_length=50)),
                ('Representante_Apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol_Empleados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('n_venta', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
                ('nom_producto', models.CharField(max_length=50)),
                ('cant_producto', models.IntegerField(default=0)),
                ('valor_unitario', models.IntegerField(default=0)),
                ('monto_total', models.IntegerField(default=0)),
                ('codigo_boleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyos.Boleta')),
                ('codigo_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyos.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='StockProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=90)),
                ('stock_producto', models.IntegerField(default=0)),
                ('codigo_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyos.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='razon_social_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyos.Proveedor'),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('nombre_Proveedor', models.CharField(max_length=50)),
                ('nombre_producto', models.CharField(max_length=40)),
                ('cantidad_pedida', models.IntegerField(default=0)),
                ('monto_pago', models.IntegerField(default=0)),
                ('numero_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('nom_proveedor_representante', models.CharField(max_length=30)),
                ('ape_proveedor_representante', models.CharField(max_length=30)),
                ('telefono_proveedor', models.IntegerField()),
                ('razon_social_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyos.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pago_Cliente_Moroso',
            fields=[
                ('num_pago', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('fecha_abono', models.DateField()),
                ('monto_abono', models.IntegerField()),
                ('monto_total', models.IntegerField()),
                ('codigo_boleta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='yuyos.Boleta')),
                ('numero_ficha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='yuyos.Ficha_Cliente_Moroso')),
                ('rut_cliente_moroso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='yuyos.Cliente_Moroso')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('rut_empleado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyos.Rol_Empleados')),
            ],
        ),
        migrations.AddField(
            model_name='cliente_moroso',
            name='num_ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuyos.Ficha_Cliente_Moroso'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='cod_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyos.Producto'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='n_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyos.Venta'),
        ),
    ]
