# Generated by Django 3.0.7 on 2020-07-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuyos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_moroso',
            name='num_ficha',
            field=models.CharField(max_length=5),
        ),
    ]
