# Generated by Django 3.0.6 on 2020-07-06 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuyos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_Despacho',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
                ('responzable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyos.Empleados')),
            ],
        ),
    ]
