# Generated by Django 3.0.6 on 2020-07-08 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuyos', '0002_orden_despacho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='monto_pago',
            new_name='monto_total',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='ape_proveedor_representante',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='fecha_pedido',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='nom_proveedor_representante',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='telefono_proveedor',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='codigo_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyos.Producto'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='numero_orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuyos.Orden_Despacho'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='precio_unitario',
            field=models.IntegerField(default=0),
        ),
    ]
